// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ_Df4xMmJhd77F_vNzlKuDwaPsWbI0to',
    appId: '1:759460538807:web:aa08d6530678206ac22032',
    messagingSenderId: '759460538807',
    projectId: 'tic-tac-toe-819bf',
    authDomain: 'tic-tac-toe-819bf.firebaseapp.com',
    storageBucket: 'tic-tac-toe-819bf.appspot.com',
    measurementId: 'G-M59YYX6VVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nIAI1xhUKjk4enTDDZJA2x4x-ZPyncg',
    appId: '1:759460538807:android:e936f528a1681b23c22032',
    messagingSenderId: '759460538807',
    projectId: 'tic-tac-toe-819bf',
    storageBucket: 'tic-tac-toe-819bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GQn8Nc1RPcFQpLOS0QmSljipv3t4M9w',
    appId: '1:759460538807:ios:3db0c8166d160492c22032',
    messagingSenderId: '759460538807',
    projectId: 'tic-tac-toe-819bf',
    storageBucket: 'tic-tac-toe-819bf.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1GQn8Nc1RPcFQpLOS0QmSljipv3t4M9w',
    appId: '1:759460538807:ios:3db0c8166d160492c22032',
    messagingSenderId: '759460538807',
    projectId: 'tic-tac-toe-819bf',
    storageBucket: 'tic-tac-toe-819bf.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ_Df4xMmJhd77F_vNzlKuDwaPsWbI0to',
    appId: '1:759460538807:web:665a43af7e5cf59cc22032',
    messagingSenderId: '759460538807',
    projectId: 'tic-tac-toe-819bf',
    authDomain: 'tic-tac-toe-819bf.firebaseapp.com',
    storageBucket: 'tic-tac-toe-819bf.appspot.com',
    measurementId: 'G-N5MBNQDYMJ',
  );
}
